# Generated by Django 3.2.5 on 2021-07-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker1', models.CharField(max_length=10)),
                ('ticker2', models.CharField(max_length=10)),
            ],
        ),
    ]
