# Generated by Django 3.2.5 on 2021-09-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20210805_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='SP500',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='item',
        ),
    ]
