# Generated by Django 3.2.5 on 2021-09-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20210903_1340'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sp500',
            table='stocks_sp500',
        ),
    ]
